<div class="row">
  <div class="large-12 columns" style="padding-top:3em;">
    <h3>Kebijakan Privasi</h3>
    <hr>
    <p>Jika Anda memerlukan informasi lebih lanjut atau memiliki pertanyaan tentang kebijakan privasi kami, silakan hubungi kami melalui email di <a href="&#109;&#97;&#105;&#108;&#116;&#111;:&#114;&#101;&#100;&#97;&#107;&#115;&#105;&#64;&#106;&#97;&#112;&#117;&#110;&#105;&#115;&#46;&#99;&#111;&#109;">&#82;&#101;&#100;&#97;&#107;&#115;&#105; &#74;&#97;&#112;&#117;&#110;&#105;&#115;</a>.</p>
<p>Di www.japunis.com kami menganggap kerahasiaan pengunjung kami menjadi sangat penting. Dokumen kebijakan privasi ini menjelaskan secara rinci jenis informasi pribadi yang dikumpulkan dan dicatat oleh www.japunis.com dan bagaimana kita menggunakannya.</p>
<p><b>Log Files</b><br> 
Seperti banyak situs lainnya, www.japunis.com memanfaatkan file log. File-file ini hanya mencatat pengunjung ke situs - biasanya merupakan prosedur standar untuk perusahaan hosting dan bagian dari analisis layanan hosting. Informasi di dalam file log mencakup alamat protokol internet (IP), tipe browser, Internet Service Provider (ISP), stempel tanggal / waktu, halaman referensi / keluar, dan mungkin jumlah kliknya. Informasi ini digunakan untuk menganalisis tren, mengelola situs, melacak pergerakan pengguna di sekitar situs, dan mengumpulkan informasi demografis. Alamat IP, dan informasi lainnya tidak terkait dengan informasi yang dapat diidentifikasi secara pribadi.</p>
<p><b>Cookies &amp; Web Beacons</b><br>
  www.japunis.com tidak menggunakan fitur cookies.</p>

<p><b>Kebijakan Privasi Pihak Ketiga</b><br>
Anda harus berkonsultasi dengan kebijakan privasi masing-masing dari server iklan pihak ketiga ini untuk mendapatkan informasi lebih terperinci tentang praktik mereka dan juga petunjuk tentang cara menyisih dari praktik tertentu. Kebijakan privasi www.japunis.com tidak berlaku, dan kami tidak dapat mengendalikan aktivitas, pengiklan atau situs web lainnya. Anda mungkin menemukan daftar komprehensif tentang kebijakan privasi ini dan tautannya di sini: <a href="http://www.privacypolicyonline.com/privacy-policy-links" title="Privacy Policy Links">Privacy Policy Links</a>.</p>
<p>Jika Anda ingin menonaktifkan cookies, Anda dapat melakukannya melalui opsi peramban individual Anda. Informasi lebih rinci tentang pengelolaan cookie dengan peramban web tertentu dapat ditemukan di situs web masing-masing browser. <a href="http://www.privacypolicyonline.com/what-are-cookies">What Are Cookies?</a></p>

<p><strong>Informasi Perlindungan Anak</strong><br />
  Kami percaya bahwa penting untuk memberikan perlindungan tambahan bagi anak-anak secara online. Kami mendorong orang tua dan wali untuk meluangkan waktu secara online dengan anak-anak mereka untuk mengamati, berpartisipasi dan / atau memantau dan membimbing aktivitas online mereka. Www.japunis.com tidak secara sadar mengumpulkan informasi identitas pribadi dari anak-anak di bawah usia 13. Jika orang tua atau wali percaya bahwa www.japunis.com memiliki database dalam informasi pengenal pribadi anak di bawah usia 13 tahun , Segera hubungi kami (menggunakan kontak di paragraf pertama) dan kami akan menggunakan usaha terbaik kami untuk segera menghapus informasi tersebut dari catatan kami.
<p>
<b>Kebijakan Privasi Khusus Online</b><br />
Kebijakan privasi ini hanya berlaku untuk aktivitas online kami dan berlaku bagi pengunjung situs kami dan mengenai informasi yang dibagikan dan / atau dikumpulkan di sana. Kebijakan ini tidak berlaku untuk informasi yang dikumpulkan secara offline atau melalui saluran selain situs web ini.</p>
<p><b>Izin</b><br />
Dengan menggunakan situs kami, Anda dengan ini menyetujui kebijakan privasi kami dan menyetujui persyaratannya.</p><p><b>Update</b><br />
  Kebijakan Privasi ini terakhir diperbaharui pada: Jumat, 28 Juli 2017.<a href="http://www.PrivacyPolicyOnline.com" title="PrivacyPolicyOnline.com Approved Site" target="_blank"><img src="http://www.privacypolicyonline.com/images/privacypolicyonline-seal.png" border="0" alt="Privacy Policy Online Approved Site" align="right" /></a><br />
  <em>Jika kami memperbarui, mengubah atau membuat perubahan pada kebijakan privasi kami, perubahan tersebut akan diposkan di sini.</em>
  <br /><br />
</p>
<!-- END of Privacy Policy || Generated by http://www.PrivacyPolicyOnline.com || -->
  </div>
</div>
<!--//contain row after container//-->
